DROP DATABASE ADVENTURE_FUNDA;

CREATE DATABASE ADVENTURE_FUNDA;

USE ADVENTURE_FUNDA;

CREATE TABLE ADMIN_INFO (
	ID INT(12) AUTO_INCREMENT,
	USER_NAME VARCHAR(50) UNIQUE, 
	PASSWORD VARCHAR(200) NOT NULL,
	EMAIL_ID VARCHAR(50) UNIQUE, 
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	MOBILE_NO VARCHAR(20),
	ADMIN_TYPE CHAR(12) NOT NULL DEFAULT 'ADMIN',
	STATUS CHAR(10) NOT NULL DEFAULT 'CREATED',
	REASON VARCHAR(500),
	LAST_LOGIN_DATE DATETIME,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE USER_INFO (
	ID INT(12) AUTO_INCREMENT,
	USER_NAME VARCHAR(50) UNIQUE,
	EMAIL_ID VARCHAR(50) UNIQUE, 	
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PASSWORD VARCHAR(50) NOT NULL,
	MOBILE_NO VARCHAR(20),
	GENDER CHAR(12),
	DOB VARCHAR(10),
	COUNTRY VARCHAR(100),
	STATE VARCHAR(100),
	CITY VARCHAR(100),
	ZIPCODE VARCHAR(20),
	OTP CHAR(20),
	GUEST_USER CHAR(20),
	ACCUMULATED_POINTS INT(10),
	REFERAL_CODE CHAR(12),
	REFERED_CODE CHAR(12),
	VERIFICATION_STATUS CHAR(10), 
	STATUS CHAR(10) NOT NULL DEFAULT 'REGISTERED',
	REASON VARCHAR(500),
	LAST_LOGIN_DATE DATETIME,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE PARTNER_INFO (
	ID INT(12) AUTO_INCREMENT,
	USER_NAME VARCHAR(50) UNIQUE, 
	EMAIL_ID VARCHAR(50) UNIQUE, 
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PASSWORD VARCHAR(50) NOT NULL,
	MOBILE_NO VARCHAR(20),
	ALTERNATIVE_NO VARCHAR(20),
	GENDER CHAR(12),
	DOB VARCHAR(10),
	COUNTRY VARCHAR(100),
	STATE VARCHAR(100),
	CITY VARCHAR(100),
	ZIPCODE VARCHAR(20),
	OTP CHAR(20),
	VERIFICATION_STATUS CHAR(10), 
	STATUS CHAR(15) NOT NULL default 'REGISTERED',
	REASON VARCHAR(500),
	PARTNER_TYPE CHAR(20), 
	ORGANIZATION_NAME VARCHAR(200),
	MERCHANT_DESCRIPTION VARCHAR(1000),
	WEBSITE_ADDRESS VARCHAR(100),
	LAST_LOGIN_DATE DATETIME,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE EVENT_INFO (
	EVENT_ID INT(12) AUTO_INCREMENT,
	EVENT_NAME VARCHAR(100) NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME,
	SHORT_DESCRIPTION VARCHAR(1000) NOT NULL,
	ADMIN_QUOTED_PRICE INT(10),
	MAX_NO_OF_PARTICIPANTS INT(5) NOT NULL,
	MIN_NO_OF_PARTICIPANTS INT(5) NOT NULL,
	NO_OF_BATCHES INT(3) NOT NULL,
	EVENT_STATUS CHAR(10) NOT NULL default 'CREATED',
	REASON VARCHAR(500),
	DIFFICULTY_GRADE CHAR(1),
	FITNESS_LEVEL CHAR(1),
	EVENT_TYPE VARCHAR(50),
	VIEW_COUNT INT(8),
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (EVENT_ID)
);

CREATE TABLE EVENT_ORGANIZERS (
    EVENT_ORGANIZER_ID INT(12) AUTO_INCREMENT,
	EVENT_ID INT(12) REFERENCES EVENT_INFO(EVENT_ID),
	ADMIN_ID VARCHAR(50),
	PARTNER_ID VARCHAR(50), 	
	PARTNER_QUOTED_PRICE INT(10) NOT NULL,
	PAYMENT_LAST_DATE DATETIME,
	MEDICAL_CERTIFICATE_STATUS CHAR(10) NOT NULL,
	EVENT_LOCATION VARCHAR(100),
	CITY VARCHAR(100),
	STATE VARCHAR(100),
	COUNTRY VARCHAR(100),
	ZIPCODE VARCHAR(20),
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (EVENT_ORGANIZER_ID)
);

/*,
	CONSTRAINT `FK_CONSTRAINT_EVENT_ID` FOREIGN KEY `EVENT_ORGANIZERS` (`EVENT_ID`) REFERENCES `ADVENTURE_FUNDA`.`EVENT_INFO` (`EVENT_ID`),
	CONSTRAINT `FK_CONSTRAINT_PARTNER_ID` FOREIGN KEY `EVENT_ORGANIZERS` (`PARTNER_ID`) REFERENCES `ADVENTURE_FUNDA`.`PARTNER_INFO` (`ID`),
	CONSTRAINT `FK_CONSTRAINT_ADMIN_ID` FOREIGN KEY `EVENT_ORGANIZERS` (`ADMIN_ID`) REFERENCES `ADVENTURE_FUNDA`.`ADMIN_INFO` (`ID`)
);*/


CREATE TABLE EVENT_REGISTRATION_INFO (
	EVENT_REGISTRATION_ID INT(12) AUTO_INCREMENT,
	USER_NAME VARCHAR(50), 
	PARTNER_ID VARCHAR(50), 
	EVENT_ID INT(12),
	NO_OF_PARTICIPANTS INT(4) NOT NULL default 1,
	EVENT_PRICE INT(10),
	EVENT_RATING INT(1),
	STATUS CHAR(15) NOT NULL default 'REGISTERED',
	REASON VARCHAR(500),
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	PRIMARY KEY (EVENT_REGISTRATION_ID)
);

/*,
	CONSTRAINT `FK_CONSTRAINT_USER_ID` FOREIGN KEY `EVENT_REGISTRATION_INFO` (`USER_NAME`) REFERENCES `ADVENTURE_FUNDA`.`USER_INFO` (`ID`),
	CONSTRAINT `FK_CONSTRAINT_PARTNER_ID1` FOREIGN KEY `EVENT_REGISTRATION_INFO` (`PARTNER_ID`) REFERENCES `ADVENTURE_FUNDA`.`PARTNER_INFO` (`ID`),
	CONSTRAINT `FK_CONSTRAINT_EVENT_ID1` FOREIGN KEY `EVENT_REGISTRATION_INFO` (`EVENT_ID`) REFERENCES `ADVENTURE_FUNDA`.`EVENT_INFO` (`EVENT_ID`)	
);*/

CREATE TABLE PAGE_HITS (
	ID INT(12) AUTO_INCREMENT,
	HIT_COUNT INT(12),
	PAGE_HIT_DATE VARCHAR(10) UNIQUE,
	PRIMARY KEY (ID)
);